apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisclusters.jgaskins.dev
spec:
  group: jgaskins.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  default: 1Gi
                replicas:
                  type: integer
                  minimum: 1
            status:
              type: object
              default: {}
              properties:
                master:
                  type: integer
                  minimum: 1
                  default: 1
  scope: Namespaced
  names:
    plural: redisclusters
    singular: rediscluster
    kind: RedisCluster
    shortNames:
      - rcl

