apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redisdbs.jgaskins.dev
spec:
  group: jgaskins.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: string
                  default: 1Gi
  scope: Namespaced
  names:
    plural: redisdbs
    singular: redisdb
    kind: RedisDB
    shortNames:
      - rdb

