name: Build Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKER_LOGIN }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Build branch image
      run: docker build . --file Dockerfile --tag jgaskins/redis-cluster-operator:${{ github.head_ref }}
      if: ${{ github.ref_type == 'branch' || github.ref_type == 'tag' }}
    - name: Push branch image
      run: docker push jgaskins/redis-cluster-operator:${{ github.head_ref }}
      if: ${{ github.ref_type == 'branch' || github.ref_type == 'tag' }}
